### ISSUE TITLE
programmatic routing

### ISSUE THREAD

**Issue by joshua1** [GiorgosK/svelte-page-transitions#1]
Hi @GiorgosK  Thanks for this example. I wanted to ask by the way , how is programmatic routing done using this svelte-kit template. The likes of "goto" method in sapper

**Comment by GiorgosK** [comment]
@joshua1 I am not sure what you mean
but your best bet for SvelteKit is the Discord channel for svelte at this point (since SvelteKit is not released and there is no official support for it)

**Comment by joshua1** [comment]
I will check on The discord channel then . I was actually referring to something like this 
```
import { goto } from '@sapper/app';

const navigateAndSave = async () => {
	await goto('/');
	saveItem();
}
```
the runtime has this (goto method)  in @sveltejs/kit/assets/runtime/navigation.js , but provides no way to import and use it
